version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: handwerkpro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI

  s3mock:
    image: adobe/s3mock:latest
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=handwerkpro
      - debug=true
    ports:
      - "9090:9090" # HTTP endpoint
      - "9191:9191" # HTTPS endpoint (optional)
    volumes:
      - ./locals3root:/containers3root

volumes:
  postgres_data:
